import { wait } from "./util";

export type ToDo = {
  id: string;
  text: string;
};
export const data: ToDo[] = [
  { id: "1", text: "Todo item 1" },
  { id: "2", text: "Todo item 2" },
  { id: "3", text: "Todo item 3" },
  { id: "4", text: "Todo item 4" },
  { id: "5", text: "Todo item 5" },
  { id: "6", text: "Todo item 6" },
  { id: "7", text: "Todo item 7" },
  { id: "8", text: "Todo item 8" },
  { id: "9", text: "Todo item 9" },
  { id: "10", text: "Todo item 10" },
  { id: "11", text: "Todo item 11" },
  { id: "12", text: "Todo item 12" },
  { id: "13", text: "Todo item 13" },
  { id: "14", text: "Todo item 14" },
  { id: "15", text: "Todo item 15" },
  { id: "16", text: "Todo item 16" },
  { id: "17", text: "Todo item 17" },
  { id: "18", text: "Todo item 18" },
  { id: "19", text: "Todo item 19" },
  { id: "20", text: "Todo item 20" },
  { id: "21", text: "Todo item 21" },
  { id: "22", text: "Todo item 22" },
  { id: "23", text: "Todo item 23" },
  { id: "24", text: "Todo item 24" },
  { id: "25", text: "Todo item 25" },
  { id: "26", text: "Todo item 26" },
  { id: "27", text: "Todo item 27" },
  { id: "28", text: "Todo item 28" },
  { id: "29", text: "Todo item 29" },
  { id: "30", text: "Todo item 30" },
  { id: "31", text: "Todo item 31" },
  { id: "32", text: "Todo item 32" },
  { id: "33", text: "Todo item 33" },
  { id: "34", text: "Todo item 34" },
  { id: "35", text: "Todo item 35" },
  { id: "36", text: "Todo item 36" },
  { id: "37", text: "Todo item 37" },
  { id: "38", text: "Todo item 38" },
  { id: "39", text: "Todo item 39" },
  { id: "40", text: "Todo item 40" },
  { id: "41", text: "Todo item 41" },
  { id: "42", text: "Todo item 42" },
  { id: "43", text: "Todo item 43" },
  { id: "44", text: "Todo item 44" },
  { id: "45", text: "Todo item 45" },
  { id: "46", text: "Todo item 46" },
  { id: "47", text: "Todo item 47" },
  { id: "48", text: "Todo item 48" },
  { id: "49", text: "Todo item 49" },
  { id: "50", text: "Todo item 50" },
  { id: "51", text: "Todo item 51" },
  { id: "52", text: "Todo item 52" },
  { id: "53", text: "Todo item 53" },
  { id: "54", text: "Todo item 54" },
  { id: "55", text: "Todo item 55" },
  { id: "56", text: "Todo item 56" },
  { id: "57", text: "Todo item 57" },
  { id: "58", text: "Todo item 58" },
  { id: "59", text: "Todo item 59" },
  { id: "60", text: "Todo item 60" },
  { id: "61", text: "Todo item 61" },
  { id: "62", text: "Todo item 62" },
  { id: "63", text: "Todo item 63" },
  { id: "64", text: "Todo item 64" },
  { id: "65", text: "Todo item 65" },
  { id: "66", text: "Todo item 66" },
  { id: "67", text: "Todo item 67" },
  { id: "68", text: "Todo item 68" },
  { id: "69", text: "Todo item 69" },
  { id: "70", text: "Todo item 70" },
  { id: "71", text: "Todo item 71" },
  { id: "72", text: "Todo item 72" },
  { id: "73", text: "Todo item 73" },
  { id: "74", text: "Todo item 74" },
  { id: "75", text: "Todo item 75" },
  { id: "76", text: "Todo item 76" },
  { id: "77", text: "Todo item 77" },
  { id: "78", text: "Todo item 78" },
  { id: "79", text: "Todo item 79" },
  { id: "80", text: "Todo item 80" },
  { id: "81", text: "Todo item 81" },
  { id: "82", text: "Todo item 82" },
  { id: "83", text: "Todo item 83" },
  { id: "84", text: "Todo item 84" },
  { id: "85", text: "Todo item 85" },
  { id: "86", text: "Todo item 86" },
  { id: "87", text: "Todo item 87" },
  { id: "88", text: "Todo item 88" },
  { id: "89", text: "Todo item 89" },
  { id: "90", text: "Todo item 90" },
  { id: "91", text: "Todo item 91" },
  { id: "92", text: "Todo item 92" },
  { id: "93", text: "Todo item 93" },
  { id: "94", text: "Todo item 94" },
  { id: "95", text: "Todo item 95" },
  { id: "96", text: "Todo item 96" },
  { id: "97", text: "Todo item 97" },
  { id: "98", text: "Todo item 98" },
  { id: "99", text: "Todo item 99" },
  { id: "100", text: "Todo item 100" },
  { id: "101", text: "Todo item 101" },
  { id: "102", text: "Todo item 102" },
  { id: "103", text: "Todo item 103" },
];

export async function getData(page: number) {
  const start = (page - 1) * 15;
  const end = page * 15;
  await wait(3000);
  return data.slice(start, end);
}
